version: '3'

services:
  vk-telegram:
    build: ./vk-telegram
    depends_on:
     - redis
    links:
      - redis
    networks:
      - mynetwork
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork: